# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/save/Work/Dobrika-SearchEngine

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/save/Work/Dobrika-SearchEngine

#=============================================================================
# Targets provided globally by CMake.


simple_build:
	cmake --build build -j --target dobrika_server_main
# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/save/Work/Dobrika-SearchEngine/CMakeFiles /home/save/Work/Dobrika-SearchEngine//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/save/Work/Dobrika-SearchEngine/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named dobrika_search

# Build rule for target.
dobrika_search: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 dobrika_search
.PHONY : dobrika_search

# fast build rule for target.
dobrika_search/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dobrika_search.dir/build.make CMakeFiles/dobrika_search.dir/build
.PHONY : dobrika_search/fast

#=============================================================================
# Target rules for targets named dse_tests

# Build rule for target.
dse_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 dse_tests
.PHONY : dse_tests

# fast build rule for target.
dse_tests/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dse_tests.dir/build.make CMakeFiles/dse_tests.dir/build
.PHONY : dse_tests/fast

#=============================================================================
# Target rules for targets named Catch2

# Build rule for target.
Catch2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Catch2
.PHONY : Catch2

# fast build rule for target.
Catch2/fast:
	$(MAKE) $(MAKESILENT) -f _deps/catch2-build/src/CMakeFiles/Catch2.dir/build.make _deps/catch2-build/src/CMakeFiles/Catch2.dir/build
.PHONY : Catch2/fast

#=============================================================================
# Target rules for targets named Catch2WithMain

# Build rule for target.
Catch2WithMain: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Catch2WithMain
.PHONY : Catch2WithMain

# fast build rule for target.
Catch2WithMain/fast:
	$(MAKE) $(MAKESILENT) -f _deps/catch2-build/src/CMakeFiles/Catch2WithMain.dir/build.make _deps/catch2-build/src/CMakeFiles/Catch2WithMain.dir/build
.PHONY : Catch2WithMain/fast

DSRequest.pb.o: DSRequest.pb.cc.o
.PHONY : DSRequest.pb.o

# target to build an object file
DSRequest.pb.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dobrika_search.dir/build.make CMakeFiles/dobrika_search.dir/DSRequest.pb.cc.o
.PHONY : DSRequest.pb.cc.o

DSRequest.pb.i: DSRequest.pb.cc.i
.PHONY : DSRequest.pb.i

# target to preprocess a source file
DSRequest.pb.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dobrika_search.dir/build.make CMakeFiles/dobrika_search.dir/DSRequest.pb.cc.i
.PHONY : DSRequest.pb.cc.i

DSRequest.pb.s: DSRequest.pb.cc.s
.PHONY : DSRequest.pb.s

# target to generate assembly for a file
DSRequest.pb.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dobrika_search.dir/build.make CMakeFiles/dobrika_search.dir/DSRequest.pb.cc.s
.PHONY : DSRequest.pb.cc.s

DSResponse.pb.o: DSResponse.pb.cc.o
.PHONY : DSResponse.pb.o

# target to build an object file
DSResponse.pb.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dobrika_search.dir/build.make CMakeFiles/dobrika_search.dir/DSResponse.pb.cc.o
.PHONY : DSResponse.pb.cc.o

DSResponse.pb.i: DSResponse.pb.cc.i
.PHONY : DSResponse.pb.i

# target to preprocess a source file
DSResponse.pb.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dobrika_search.dir/build.make CMakeFiles/dobrika_search.dir/DSResponse.pb.cc.i
.PHONY : DSResponse.pb.cc.i

DSResponse.pb.s: DSResponse.pb.cc.s
.PHONY : DSResponse.pb.s

# target to generate assembly for a file
DSResponse.pb.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dobrika_search.dir/build.make CMakeFiles/dobrika_search.dir/DSResponse.pb.cc.s
.PHONY : DSResponse.pb.cc.s

DServer.pb.o: DServer.pb.cc.o
.PHONY : DServer.pb.o

# target to build an object file
DServer.pb.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dobrika_search.dir/build.make CMakeFiles/dobrika_search.dir/DServer.pb.cc.o
.PHONY : DServer.pb.cc.o

DServer.pb.i: DServer.pb.cc.i
.PHONY : DServer.pb.i

# target to preprocess a source file
DServer.pb.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dobrika_search.dir/build.make CMakeFiles/dobrika_search.dir/DServer.pb.cc.i
.PHONY : DServer.pb.cc.i

DServer.pb.s: DServer.pb.cc.s
.PHONY : DServer.pb.s

# target to generate assembly for a file
DServer.pb.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dobrika_search.dir/build.make CMakeFiles/dobrika_search.dir/DServer.pb.cc.s
.PHONY : DServer.pb.cc.s

src/Components/xapian_processor/xapian_processor.o: src/Components/xapian_processor/xapian_processor.cpp.o
.PHONY : src/Components/xapian_processor/xapian_processor.o

# target to build an object file
src/Components/xapian_processor/xapian_processor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dobrika_search.dir/build.make CMakeFiles/dobrika_search.dir/src/Components/xapian_processor/xapian_processor.cpp.o
.PHONY : src/Components/xapian_processor/xapian_processor.cpp.o

src/Components/xapian_processor/xapian_processor.i: src/Components/xapian_processor/xapian_processor.cpp.i
.PHONY : src/Components/xapian_processor/xapian_processor.i

# target to preprocess a source file
src/Components/xapian_processor/xapian_processor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dobrika_search.dir/build.make CMakeFiles/dobrika_search.dir/src/Components/xapian_processor/xapian_processor.cpp.i
.PHONY : src/Components/xapian_processor/xapian_processor.cpp.i

src/Components/xapian_processor/xapian_processor.s: src/Components/xapian_processor/xapian_processor.cpp.s
.PHONY : src/Components/xapian_processor/xapian_processor.s

# target to generate assembly for a file
src/Components/xapian_processor/xapian_processor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dobrika_search.dir/build.make CMakeFiles/dobrika_search.dir/src/Components/xapian_processor/xapian_processor.cpp.s
.PHONY : src/Components/xapian_processor/xapian_processor.cpp.s

src/static.o: src/static.cpp.o
.PHONY : src/static.o

# target to build an object file
src/static.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dobrika_search.dir/build.make CMakeFiles/dobrika_search.dir/src/static.cpp.o
.PHONY : src/static.cpp.o

src/static.i: src/static.cpp.i
.PHONY : src/static.i

# target to preprocess a source file
src/static.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dobrika_search.dir/build.make CMakeFiles/dobrika_search.dir/src/static.cpp.i
.PHONY : src/static.cpp.i

src/static.s: src/static.cpp.s
.PHONY : src/static.s

# target to generate assembly for a file
src/static.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dobrika_search.dir/build.make CMakeFiles/dobrika_search.dir/src/static.cpp.s
.PHONY : src/static.cpp.s

src/tools/config_generator.o: src/tools/config_generator.cpp.o
.PHONY : src/tools/config_generator.o

# target to build an object file
src/tools/config_generator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dobrika_search.dir/build.make CMakeFiles/dobrika_search.dir/src/tools/config_generator.cpp.o
.PHONY : src/tools/config_generator.cpp.o

src/tools/config_generator.i: src/tools/config_generator.cpp.i
.PHONY : src/tools/config_generator.i

# target to preprocess a source file
src/tools/config_generator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dobrika_search.dir/build.make CMakeFiles/dobrika_search.dir/src/tools/config_generator.cpp.i
.PHONY : src/tools/config_generator.cpp.i

src/tools/config_generator.s: src/tools/config_generator.cpp.s
.PHONY : src/tools/config_generator.s

# target to generate assembly for a file
src/tools/config_generator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dobrika_search.dir/build.make CMakeFiles/dobrika_search.dir/src/tools/config_generator.cpp.s
.PHONY : src/tools/config_generator.cpp.s

src/tools/dse_tools.o: src/tools/dse_tools.cpp.o
.PHONY : src/tools/dse_tools.o

# target to build an object file
src/tools/dse_tools.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dobrika_search.dir/build.make CMakeFiles/dobrika_search.dir/src/tools/dse_tools.cpp.o
.PHONY : src/tools/dse_tools.cpp.o

src/tools/dse_tools.i: src/tools/dse_tools.cpp.i
.PHONY : src/tools/dse_tools.i

# target to preprocess a source file
src/tools/dse_tools.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dobrika_search.dir/build.make CMakeFiles/dobrika_search.dir/src/tools/dse_tools.cpp.i
.PHONY : src/tools/dse_tools.cpp.i

src/tools/dse_tools.s: src/tools/dse_tools.cpp.s
.PHONY : src/tools/dse_tools.s

# target to generate assembly for a file
src/tools/dse_tools.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dobrika_search.dir/build.make CMakeFiles/dobrika_search.dir/src/tools/dse_tools.cpp.s
.PHONY : src/tools/dse_tools.cpp.s

tests/test_backup.o: tests/test_backup.cpp.o
.PHONY : tests/test_backup.o

# target to build an object file
tests/test_backup.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dse_tests.dir/build.make CMakeFiles/dse_tests.dir/tests/test_backup.cpp.o
.PHONY : tests/test_backup.cpp.o

tests/test_backup.i: tests/test_backup.cpp.i
.PHONY : tests/test_backup.i

# target to preprocess a source file
tests/test_backup.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dse_tests.dir/build.make CMakeFiles/dse_tests.dir/tests/test_backup.cpp.i
.PHONY : tests/test_backup.cpp.i

tests/test_backup.s: tests/test_backup.cpp.s
.PHONY : tests/test_backup.s

# target to generate assembly for a file
tests/test_backup.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dse_tests.dir/build.make CMakeFiles/dse_tests.dir/tests/test_backup.cpp.s
.PHONY : tests/test_backup.cpp.s

tests/test_xapian_layer.o: tests/test_xapian_layer.cpp.o
.PHONY : tests/test_xapian_layer.o

# target to build an object file
tests/test_xapian_layer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dse_tests.dir/build.make CMakeFiles/dse_tests.dir/tests/test_xapian_layer.cpp.o
.PHONY : tests/test_xapian_layer.cpp.o

tests/test_xapian_layer.i: tests/test_xapian_layer.cpp.i
.PHONY : tests/test_xapian_layer.i

# target to preprocess a source file
tests/test_xapian_layer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dse_tests.dir/build.make CMakeFiles/dse_tests.dir/tests/test_xapian_layer.cpp.i
.PHONY : tests/test_xapian_layer.cpp.i

tests/test_xapian_layer.s: tests/test_xapian_layer.cpp.s
.PHONY : tests/test_xapian_layer.s

# target to generate assembly for a file
tests/test_xapian_layer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dse_tests.dir/build.make CMakeFiles/dse_tests.dir/tests/test_xapian_layer.cpp.s
.PHONY : tests/test_xapian_layer.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... Catch2"
	@echo "... Catch2WithMain"
	@echo "... dobrika_search"
	@echo "... dse_tests"
	@echo "... DSRequest.pb.o"
	@echo "... DSRequest.pb.i"
	@echo "... DSRequest.pb.s"
	@echo "... DSResponse.pb.o"
	@echo "... DSResponse.pb.i"
	@echo "... DSResponse.pb.s"
	@echo "... DServer.pb.o"
	@echo "... DServer.pb.i"
	@echo "... DServer.pb.s"
	@echo "... src/Components/xapian_processor/xapian_processor.o"
	@echo "... src/Components/xapian_processor/xapian_processor.i"
	@echo "... src/Components/xapian_processor/xapian_processor.s"
	@echo "... src/static.o"
	@echo "... src/static.i"
	@echo "... src/static.s"
	@echo "... src/tools/config_generator.o"
	@echo "... src/tools/config_generator.i"
	@echo "... src/tools/config_generator.s"
	@echo "... src/tools/dse_tools.o"
	@echo "... src/tools/dse_tools.i"
	@echo "... src/tools/dse_tools.s"
	@echo "... tests/test_backup.o"
	@echo "... tests/test_backup.i"
	@echo "... tests/test_backup.s"
	@echo "... tests/test_xapian_layer.o"
	@echo "... tests/test_xapian_layer.i"
	@echo "... tests/test_xapian_layer.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system


#=============================================================================
# Custom convenience targets
.PHONY : configure_release_server reconfigure_clean build_server_main run_server build_http_tests run_http_tests full_server

configure_release_server:
	$(CMAKE_COMMAND) -S /home/save/Work/Dobrika-SearchEngine -B /home/save/Work/Dobrika-SearchEngine/build -DCMAKE_BUILD_TYPE=Release -DDOBRIKA_WITH_SERVER=ON

reconfigure_clean:
	/usr/bin/cmake -E rm -rf /home/save/Work/Dobrika-SearchEngine/build
	$(MAKE) $(MAKESILENT) configure_release_server

build_server_main: configure_release_server
	$(CMAKE_COMMAND) --build /home/save/Work/Dobrika-SearchEngine/build -j --target dobrika_server_main

run_server: build_server_main
	/home/save/Work/Dobrika-SearchEngine/build/dobrika_server_main

build_http_tests: configure_release_server
	$(CMAKE_COMMAND) --build /home/save/Work/Dobrika-SearchEngine/build -j --target dse_http_tests

run_http_tests: build_http_tests
	/home/save/Work/Dobrika-SearchEngine/build/dse_http_tests

full_server: build_server_main run_server

# Format all C/C++ sources in the repository using clang-format.
.PHONY : format
format:
	@command -v clang-format >/dev/null 2>&1 || { echo "clang-format not found. Please install clang-format."; exit 1; }
	@files=$$(find src tests -type f \( -name '*.c' -o -name '*.cc' -o -name '*.cpp' -o -name '*.h' -o -name '*.hpp' \) 2>/dev/null); \
	if [ -n "$$files" ]; then \
		echo "Running clang-format on:"; \
		printf '%s\n' $$files; \
		clang-format -i $$files; \
	else \
		echo "No C/C++ source files found to format."; \
	fi
